const friendData = [
  {id: 1, name: 'Faye Slift'},
  {id: 2, name: 'I. P. Freely'},
  {id: 3, name: 'Jed Dye'},
  {id: 4, name: 'Marshall Law'},
  {id: 5, name: 'Miss Alanius'},
  {id: 6, name: 'Woody U. No'},
  {id: 7, name: 'Doug Graves'},
  {id: 8, name: 'Colin Allcars'},
  {id: 9, name: 'Ilene East'},
  {id: 10, name: 'Jane Linkfence'},
  {id: 11, name: 'Anna Graham'},
  {id: 12, name: 'Mel Practiss'},
  {id: 13, name: 'Ima Klotz'},
  {id: 14, name: 'Bill Loney'},
  {id: 15, name: 'Leo Tarred'},
  {id: 16, name: 'Estelle Hertz'},
  {id: 17, name: 'Woody U. No'},
  {id: 18, name: 'Rory Storm'},
  {id: 19, name: 'Dan Deline'},
  {id: 20, name: 'Claire Voyance'},
  {id: 21, name: 'Doris Open'},
  {id: 22, name: 'Shirley Knot'},
  {id: 23, name: 'Winnie Bago'},
  {id: 24, name: 'Barry D. Hatchett'},
  {id: 25, name: 'Carl Arm'},
  {id: 26, name: 'Faye Kinnitt'},
  {id: 27, name: 'Bruce Easley'},
  {id: 28, name: 'Ida Whana'},
  {id: 29, name: 'Dan Deline'},
  {id: 30, name: 'Eve Hill'},
  {id: 31, name: 'Skip Stone'},
  {id: 32, name: 'Marsha Dimes'},
  {id: 33, name: 'Joe Kerr'},
  {id: 34, name: 'Andy Gravity'},
  {id: 35, name: 'Joy Kil'},
  {id: 36, name: 'Marco DeStinkshun'},
  {id: 37, name: 'Hope Ferterbest'},
  {id: 38, name: 'Dee Liver'},
  {id: 39, name: 'Emma Royds'},
  {id: 40, name: 'Beau Tye'},
  {id: 41, name: 'Rick Shaw'},
  {id: 42, name: 'Carl Arm'},
  {id: 43, name: 'Gene E. Yuss'},
  {id: 44, name: 'Abe Rudder'},
  {id: 45, name: 'Nick L. Andime'},
  {id: 46, name: 'Sue Shi'},
  {id: 47, name: 'M. T. Toombe'},
  {id: 48, name: 'Chris P. Nugget'},
  {id: 49, name: 'Hugh Mungous'},
  {id: 50, name: 'Anne Teak'},
  {id: 51, name: 'Roger Overandout'},
  {id: 52, name: 'Rick Kleiner'},
  {id: 53, name: 'Douglas S. Halfempty'},
  {id: 54, name: 'Ann B. Dextrous'},
  {id: 55, name: 'Misty C. Shore'},
  {id: 56, name: 'P. Brain'},
  {id: 57, name: 'Ron A. Muck'},
  {id: 58, name: 'I. Ball'},
  {id: 59, name: 'Al Kaseltzer'},
  {id: 60, name: 'M. T. Toombe'},
  {id: 61, name: 'Marlon Fisher'},
  {id: 62, name: 'Jack Pott'},
  {id: 63, name: 'Ima Lytle Teapot'},
  {id: 64, name: 'Sue Render'},
  {id: 65, name: 'Thor Luther'},
  {id: 66, name: 'C. Worthy'},
  {id: 67, name: 'Roman Holiday'},
  {id: 68, name: 'Kenya Dewit'},
  {id: 69, name: 'Hal E. Luya'},
  {id: 70, name: 'Nick Ovtime'},
  {id: 71, name: 'Bill Ng'},
  {id: 72, name: 'Barry D. Hatchett'},
  {id: 73, name: "Nick O'Time"},
  {id: 74, name: 'Phil A. Delphia'},
  {id: 75, name: 'Polly Dent'},
  {id: 76, name: 'Kenny Dewitt'},
  {id: 77, name: 'Clara Sabell'},
  {id: 78, name: 'Candy Barr'},
  {id: 79, name: 'Marsha Mellow'},
  {id: 80, name: 'Eli Ondefloor'},
  {id: 81, name: 'Sheri Cola'},
  {id: 82, name: 'Carson O. Gin'},
  {id: 83, name: 'Earl E. Byrd'},
  {id: 84, name: 'Jerry Atrics'},
  {id: 85, name: 'Lina Ginster'},
  {id: 86, name: 'Renee Sance'},
  {id: 87, name: 'Tad Pohl'},
  {id: 88, name: 'Michelle Lynn'},
  {id: 89, name: 'Mike Czech'},
  {id: 90, name: 'Anna Sasin'},
  {id: 91, name: 'Taylor Maid'},
  {id: 92, name: 'Jim Sox'},
  {id: 93, name: 'Sue Jeu'},
  {id: 94, name: 'Rocky Rhoades'},
  {id: 95, name: 'Juan Fortharoad'},
  {id: 96, name: 'Olive Branch'},
  {id: 97, name: 'Otto B. Kilt'},
  {id: 98, name: 'Harry Legg'},
  {id: 99, name: 'Therese R. Green'},
  {id: 100, name: 'Juan Fortharoad'},
  {id: 101, name: 'Sawyer B. Hind'},
  {id: 102, name: 'I. Pullem'},
  {id: 103, name: 'X. Benedict'},
  {id: 104, name: 'Frank N. Beans'},
  {id: 105, name: 'Dustin D. Furniture'},
  {id: 106, name: 'Ethel L. Cahall'},
  {id: 107, name: 'M. T. Toombe'},
  {id: 108, name: 'Colette A. Day'},
  {id: 109, name: 'Ray N. Carnation'},
  {id: 110, name: 'Tom A. Toe'},
  {id: 111, name: 'Bo D. Satva'},
  {id: 112, name: 'P. Brain'},
  {id: 113, name: 'Arch N. Emmy'},
  {id: 114, name: 'Sal A. Mander'},
  {id: 115, name: 'Lynn O. Liam'},
  {id: 116, name: 'E. Ville'},
  {id: 117, name: 'Dale E. Bread'},
  {id: 118, name: 'Hal E. Luya'},
  {id: 119, name: 'Earl E. Byrd'},
  {id: 120, name: 'Yule B. Sari'},
  {id: 121, name: 'Jan U. Wharry'},
  {id: 122, name: 'Carrie A. Tune'},
  {id: 123, name: 'Max E. Mumm'},
  {id: 124, name: 'Ben D. Fender'},
  {id: 125, name: 'Tom A. Toe'},
  {id: 126, name: 'Frank N. Beans'},
  {id: 127, name: 'I. Pullem'},
  {id: 128, name: 'Morgan U. Canhandle'},
  {id: 129, name: 'Al B. Tross'},
  {id: 130, name: 'Pearl E. Whites'},
  {id: 131, name: 'P. Brain'},
  {id: 132, name: 'Chris P. Nugget'},
  {id: 133, name: 'Howe D. Pardner'},
  {id: 134, name: 'Howe D. Pardner'},
  {id: 135, name: 'R. M. Pitt'},
  {id: 136, name: 'Otto B. Kilt'},
  {id: 137, name: 'Mary A. Richman'},
  {id: 138, name: 'B. A. Ware'},
  {id: 139, name: 'Doll R. Bill'},
  {id: 140, name: 'Gladys C. Hughes'},
  {id: 141, name: 'Sharon A. Burger'},
  {id: 142, name: 'Bertha D. Blues'},
  {id: 143, name: 'Chris P. Bacon'},
  {id: 144, name: 'Carrie A. Tune'},
  {id: 145, name: 'C. Worthy'},
  {id: 146, name: 'Hal E. Luya'},
  {id: 147, name: 'Howard I. No'},
  {id: 148, name: 'Louise E. Anna'},
  {id: 149, name: 'Pearl E. Whites'},
  {id: 150, name: 'Ron A. Muck'},
  {id: 151, name: 'Dan D. Lyon'},
  {id: 152, name: 'Brandy D. Cantor'},
  {id: 153, name: 'Ben D. Fender'},
  {id: 154, name: 'Al K. Seltzer'},
  {id: 155, name: 'Dustin D. Furniture'},
  {id: 156, name: 'I. P. Freely'},
  {id: 157, name: 'Kenney C. Strait'},
  {id: 158, name: 'Ricky T. Ladder'},
  {id: 159, name: 'Mark Z. Spot'},
  {id: 160, name: 'I. P. Daly'},
  {id: 161, name: 'Lynn O. Liam'},
  {id: 162, name: 'Howe D. Pardner'},
  {id: 163, name: 'Jan U. Wharry'},
  {id: 164, name: 'Warren T.'},
  {id: 165, name: 'Al K. Seltzer'},
  {id: 166, name: 'Chris P. Nugget'},
  {id: 167, name: 'B. A. Ware'},
  {id: 168, name: 'Bo D. Satva'},
  {id: 169, name: 'Brandy D. Cantor'},
  {id: 170, name: 'Max E. Mumm'},
  {id: 171, name: 'Mary A. Richman'},
  {id: 172, name: 'Gil T. Azell'},
  {id: 173, name: 'Ted E. Baer'},
  {id: 174, name: 'I. Ball'},
  {id: 175, name: 'Ima B. Leever'},
  {id: 176, name: 'Chris P. Wheatzenraisins'},
  {id: 177, name: 'Colette A. Day'},
  {id: 178, name: 'Park A. Studebaker'},
  {id: 179, name: 'Zeke N. Yeshallfind'},
  {id: 180, name: 'I. Ron Stomach'},
  {id: 181, name: 'R. M. Pitt'},
  {id: 182, name: 'Gladys C. Hughes'},
  {id: 183, name: 'Gladys C. Hughes'},
  {id: 184, name: 'Rob A. Bank'},
  {id: 185, name: 'Earl E. Byrd'},
  {id: 186, name: 'Neil B. Formy'},
  {id: 187, name: 'I. Ball'},
  {id: 188, name: 'Neil B. Formy'},
  {id: 189, name: 'Howe D. Pardner'},
  {id: 190, name: 'M. T. Toombe'},
  {id: 191, name: 'Maude L. T. Ford'},
  {id: 192, name: 'Phil A. Delphia'},
  {id: 193, name: 'Louise E. Anna'},
  {id: 194, name: 'Chris P. Bacon'},
  {id: 195, name: 'Pearl E. Whites'},
  {id: 196, name: 'I. D. Clair'},
  {id: 197, name: 'Dustin D. Furniture'},
  {id: 198, name: 'Dale E. Bread'},
  {id: 199, name: 'Woody U. No'},
  {id: 200, name: 'I. Pullem'},
];

export default friendData;
